# Generated by Django 2.2.2 on 2019-06-20 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miexamen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('cod_examen', models.AutoField(primary_key=True, serialize=False)),
                ('rut_entidad', models.CharField(max_length=20)),
                ('rut_paciente', models.CharField(max_length=20)),
                ('estado', models.CharField(max_length=200)),
                ('rut_especialista', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ListaExamen',
            fields=[
                ('cod_examen', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='listado',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='listado',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Tienda',
        ),
        migrations.DeleteModel(
            name='Listado',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
