# Generated by Django 2.2.2 on 2019-06-20 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miexamen', '0002_auto_20190620_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='examen',
            name='fecha_entrega',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='examen',
            name='fecha_solicitud',
            field=models.DateField(null=True),
        ),
    ]
