# Generated by Django 2.2.2 on 2019-06-20 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miexamen', '0003_auto_20190620_1428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examen',
            name='fecha_solicitud',
        ),
    ]
