# Generated by Django 2.2.2 on 2019-06-20 18:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miexamen', '0004_remove_examen_fecha_solicitud'),
    ]

    operations = [
        migrations.AddField(
            model_name='examen',
            name='fecha_solicitud',
            field=models.DateField(null=True, verbose_name=datetime.datetime.now),
        ),
    ]
