# Generated by Django 2.2.2 on 2019-06-21 03:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miexamen', '0005_examen_fecha_solicitud'),
    ]

    operations = [
        migrations.AddField(
            model_name='examen',
            name='tipo_examen',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='miexamen.ListaExamen'),
        ),
        migrations.AlterField(
            model_name='examen',
            name='estado',
            field=models.CharField(default='En curso', max_length=200),
        ),
        migrations.AlterField(
            model_name='examen',
            name='fecha_entrega',
            field=models.DateField(default=datetime.datetime(2019, 7, 20, 23, 17, 57, 729629), null=True),
        ),
        migrations.AlterField(
            model_name='examen',
            name='fecha_solicitud',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='examen',
            name='rut_entidad',
            field=models.CharField(default='60536429-8', max_length=20),
        ),
        migrations.AlterField(
            model_name='examen',
            name='rut_especialista',
            field=models.CharField(default='13548987-8', max_length=20),
        ),
    ]
